-- Tabela de carteiras
CREATE TABLE IF NOT EXISTS wallets (
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type    VARCHAR(20) NOT NULL CHECK (type IN ('COMMON', 'SHOPKEEPER')),
    balance DECIMAL(19,2) NOT NULL DEFAULT 0
    );

-- Tabela de clientes
CREATE TABLE IF NOT EXISTS clients (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email      VARCHAR(255) NOT NULL,
    password   VARCHAR(255) NOT NULL,
    wallet_id  BIGINT NOT NULL,
    CONSTRAINT uq_clients_email  UNIQUE (email),
    CONSTRAINT uq_clients_wallet UNIQUE (wallet_id),
    CONSTRAINT fk_clients_wallet FOREIGN KEY (wallet_id) REFERENCES wallets(id)
    );

CREATE TABLE IF NOT EXISTS transactions (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status             VARCHAR(20) NOT NULL CHECK (status IN ('CREATED', 'AUTHORIZED', 'FAILED')),
    transaction_value  DECIMAL(19,2) NOT NULL,
    payer_id           BIGINT NOT NULL,
    payee_id           BIGINT NOT NULL,
    idempotency_key    VARCHAR(64) NOT NULL UNIQUE,
    created_at         TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    authorized_at      TIMESTAMP,
    failed_at          TIMESTAMP,
    CONSTRAINT fk_transactions_payer_id FOREIGN KEY (payer_id) REFERENCES wallets(id),
    CONSTRAINT fk_transactions_payee_id FOREIGN KEY (payee_id) REFERENCES wallets(id)
)
